#! /bin/sh

##############################################
# _
#| |__  ___ _ ____      ___ __ ___  _ __ ___
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#          |_|                               
##############################################

zsh ~/.config/bspwm/killscript;

pgrep -x sxhkd > /dev/null || sxhkd &

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Set wallpaper
#watch -n 600 feh --randomize --bg-max /mnt/Data/2021/Imgs/Wallpapers/2/* &>/dev/null&
feh --randomize --bg-fill /home/trungtin/Pictures/Wallpapers/171027.jpg &>/dev/null&
$HOME/.config/polybar/launch.sh &

# Autostart
ibus-daemon -drx &
picom -c &
flameshot &
dunst &
~/.local/bin/blurwal --backend feh -m 1 &
libinput-gestures-setup start &
#pgrep -x bspswallow > /dev/null || bspswallow &
pgrep bspswallow || bspswallow &



bspc config border_width        0
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium               desktop='^2' --focus
bspc rule -a vlc                    state=floating
bspc rule -a Envince                --focus
bspc rule -a Screenkey              manage=off

bspc rule -a nautilus               state=floating
bspc rule -a xdman-Main:\*          state=floating
bspc rule -a notion-app             desktop='^3'
bspc rule -a code                   desktop='^1'

bspc rule -a kitty:Terminal         desktop=^1

#kitty --name Terminal -e nvim -s ~/Coding/ -d ~/Coding/ &
#kitty --name Myujiku -e cava &
#kitty --name Myujiku -e ncmpcpp -s lyrics &
#kitty --name Myujiku -e ncmpcpp -s playlist &

kitty -e tmux
#evince ~/Grammar_IELTS.pdf > /dev/null
