#!/bin/sh

killall bspswallow
zsh -c 'rofi -show run -font "SF Pro Display 12"'

while pidof rofi; do continue
done

bspc subscribe note_add | while read -r event; do
    bspswallow & exit
done

sleep 2
bspswallow & exit

