(function (undefined) {

    /* As for 31.03.16, Instant Translate Browsers supports:
     * 104 languages + auto
     */


    pl.extend(ke.ext.const.lang, {
        list: {
            'Auto': 'auto',
            'Afrikaans': 'af',
            'Albanian': 'sq',
            'Arabic': 'ar',
            'Armenian': 'hy',
            'Azerbaijani': 'az',
            'Basque': 'eu',
            'Belarusian': 'be',
            'Bengali': 'bn',
            'Bosnian': 'bs',
            'Bulgarian': 'bg',
            'Catalan': 'ca',
            'Cebuano': 'ceb',
            'Chichewa': 'ny',
            'ChineseSimplified': 'zh-CN',
            'ChineseTraditional': 'zh-TW',
            'Croatian': 'hr',
            'Czech': 'cs',
            'Danish': 'da',
            'Dutch': 'nl',
            'English': 'en',
            'EnglishUS': 'en-US',
            'Esperanto': 'eo',
            'Estonian': 'et',
            'Filipino': 'tl',
            'Finnish': 'fi',
            'French': 'fr',
            'Galician': 'gl',
            'Georgian': 'ka',
            'German': 'de',
            'Greek': 'el',
            'Gujarati': 'gu',
            'HaitianCreole': 'ht',
            'Hausa': 'ha',
            'Hebrew': 'iw',
            'Hindi': 'hi',
            'Hmong': 'hmn',
            'Hungarian': 'hu',
            'Icelandic': 'is',
            'Igbo': 'ig',
            'Indonesian': 'id',
            'Irish': 'ga',
            'Italian': 'it',
            'Javanese': 'jw',
            'Japanese': 'ja',
            'Kannada': 'kn',
            'Kazakh': 'kk',
            'Khmer': 'km',
            'Korean': 'ko',
            'Lao': 'lo',
            'Latin': 'la',
            'Latvian': 'lv',
            'Lithuanian': 'lt',
            'Macedonian': 'mk',
            'Malagasy': 'mg',
            'Malay': 'ms',
            'Maltese': 'mt',
            'Maori': 'mi',
            'Marathi': 'mr',
            'Mongolian': 'mn',
            'Nepali': 'ne',
            'Norwegian': 'no',
            'Persian': 'fa',
            'Polish': 'pl',
            'Portuguese': 'pt',
            'Punjabi': 'pa',
            'Romanian': 'ro',
            'Russian': 'ru',
            'Serbian': 'sr',
            'Sesotho': 'st',
            'Sinhala': 'si',
            'Slovak': 'sk',
            'Slovenian': 'sl',
            'Somali': 'so',
            'Spanish': 'es',
            'Sundanese': 'su',
            'Swahili': 'sw',
            'Swedish': 'sv',
            'Tajik': 'tg',
            'Tamil': 'ta',
            'Telugu': 'te',
            'Thai': 'th',
            'Turkish': 'tr',
            'Ukrainian': 'uk',
            'Urdu': 'ur',
            'Uzbek': 'uz',
            'Vietnamese': 'vi',
            'Welsh': 'cy',
            'Yiddish': 'yi',
            'Yoruba': 'yo',
            'Zulu': 'zu',
            'Malayalam': 'ml',
            'MyanmarBurmese': 'my',

            // v2.9.46 (+13 langs)

            'Amharic': 'am',
            'Corsican': 'co',
            'Frisian': 'fy',
            'Hawaiian': 'haw',
            'KurdishKurmanji': 'ku',
            'Kyrgyz': 'ky',
            'Luxembourgish': 'lb',
            'Pashto': 'ps',
            'Samoan': 'sm',
            'ScotsGaelic': 'gd',
            'Shona': 'sn',
            'Sindhi': 'sd',
            'Xhosa': 'xh'
        },

        // in g format
        tuFromEnum: ['en', 'en-us'],

        tuFromList: {
            'English': 'en-en',
            'EnglishUS': 'en-us'
        },

        tuEnum: [],
        tuEnumForG: [],

        tuList: {
            //'Albanian': 'sq-sq',

            /*'ArabicAlgeria': 'ar-dz',
            'ArabicBahrain': 'ar-bh',
            'ArabicEgypt': 'ar-eg',
            'ArabicGeneral': 'ar-ar',
            'ArabicIraq': 'ar-iq',
            'ArabicJordan': 'ar-jo',
            'ArabicKuwait': 'ar-kw',
            'ArabicLebanon': 'ar-lb',
            'ArabicLibyan': 'ar-ly',
            'ArabicMorocco': 'ar-ma',
            'ArabicOman': 'ar-om',
            'ArabicQatar': 'ar-qa',
            'ArabicSaudi': 'ar-sa',
            'ArabicSudan': 'ar-sd',
            'ArabicSyria': 'ar-sy',
            'ArabicTunisia': 'ar-tn',
            'ArabicUAE': 'ar-ae',
            'ArabicYemen': 'ar-ye',*/

            //'Armenian': 'hy-hy',
            //'Azerbaijani': 'az-az',
            //'Basque': 'eu-eu',
            //'Belarusian': 'be-be',
            //'Bengali': 'bn-bn',
            //'Bosnian': 'ba-ba',
            //'Bulgarian': 'bg-bg',
            //'Catalan': 'ca-ca',
            'ChineseSimplified': 'cn-cn',
            'ChineseTraditional': 'tw-tw',
            //'Croatian': 'hr-hr',
            //'Czech': 'cs-cs',
            'Danish': 'da-da',
            'DutchBelgium': 'nl-be',
            'DutchNetherlands': 'nl-nl',
            'English': 'en-en',
            'EnglishUS': 'en-us',
            //'Estonian': 'et-et',
            'Finnish': 'fi-fi',

            'FrenchBelgium': 'fr-be',
            'FrenchCanada': 'fr-ca',
            'FrenchFrance': 'fr-fr',
            'FrenchSwiss': 'fr-ch',

            //'Georgian': 'ka-ka',

            'GermanAustria': 'de-at',
            'GermanGermany': 'de-de',
            'GermanLichtenstein': 'de-li',
            'GermanLux': 'de-lu',
            'GermanSwiss': 'de-ch',

            'Greek': 'el-el',
            'Hebrew': 'he-he',
            //'Hindi': 'hi-hi',
            //'Hungarian': 'hu-hu',
            //'Icelandic': 'is-is',
            'Indonesian': 'id-id',
            'Italian': 'it-it',
            'Japanese': 'ja-ja',
            //'Kannada': 'kn-kn',
            'Korean': 'ko-ko',
            //'Latvian': 'lv-lv',
            //'Lithuanian': 'lt-lt',
            //'Macedonian': 'mk-mk',
            'Malay': 'ms-ms',
            'Norwegian': 'no-no',
            //'Persian': 'fa-fa',
            //'Polish': 'pl-pl',
            'PortugueseBrazil': 'pt-br',
            'PortuguesePortugal': 'pt-pt',
            //'Punjabi': 'pa-pa',
            //'Romanian': 'ro-ro',
            'Russian': 'ru-ru',
            //'Serbian': 'sr-sr',
            //'Slovak': 'sk-sk',
            //'Slovenian': 'sl-sl',

            'SpanishArgentina': 'es-ar',
            'SpanishBolivia': 'es-bo',
            'SpanishChile': 'es-cl',
            'SpanishColombia': 'es-co',
            'SpanishCostaRica': 'es-cr',
            'SpanishDR': 'es-do',
            'SpanishSalvador': 'es-sv',
            'SpanishEquador': 'es-ec',
            'SpanishGuatemala': 'es-gt',
            'SpanishHonduras': 'es-hn',
            'SpanishMexico': 'es-mx',
            'SpanishNicaragua': 'es-ni',
            'SpanishPanama': 'es-pa',
            'SpanishParaguay': 'es-py',
            'SpanishPeru': 'es-pe',
            'SpanishPuertoRico': 'es-pr',
            'SpanishSpain': 'es-es',
            'SpanishUS': 'es-us',
            'SpanishUruguay': 'es-uy',
            'SpanishVenezuela': 'es-ve',

            'Swedish': 'sv-sv',
            //'Telugu': 'te-te',
            'Thai': 'th-th',
            'Turkish': 'tr-tr',
            //'Ukrainian': 'uk-uk',
            'Vietnamese': 'vi-vi'
            //'Welsh': 'cy-cy'
        },

        g2tu: {
            'ar': 'ar-ar',
            'nl': 'nl-nl',
            'pt': 'pt-br',
            'es': 'es-es',
            'de': 'de-de',
            'fr': 'fr-fr'
        },

        stt: {
            'af': ['af-ZA'],
            'id': ['id-ID'],
            'ms': ['ms-MY'],
            'ca': ['ca-ES'],
            'cs': ['cs-CZ'],
            'da': ['da-DK'],
            'de': ['de-DE'],
            'en': ['en-GB'],
            'en-US': ['en-US'],
            'es': ['es-ES'],
            'eu': ['eu-ES'],
            'fil': ['fil-PH'],
            'fr': ['fr-FR'],
            'gl': ['gl-ES'],
            'hr': ['hr_HR'],
            'zu': ['zu-ZA'],
            'is': ['is-IS'],
            'it': ['it-IT'],
            'lt': ['lt-LT'],
            'hu': ['hu-HU'],
            'nl': ['nl-NL'],
            'nb': ['nb-NO'],
            'pl': ['pl-PL'],
            'pt': ['pt-BR'],
            'ro': ['ro-RO'],
            'sl': ['sl-SI'],
            'sk': ['sk-SK'],
            'fi': ['fi-FI'],
            'sv': ['sv-SE'],
            'vi': ['vi-VN'],
            'tr': ['tr-TR'],
            'el': ['el-GR'],
            'bg': ['bg-BG'],
            'ru': ['ru-RU'],
            'sr': ['sr-RS'],
            'uk': ['uk-UA'],
            'ko': ['ko-KR'],
            'zh-CN': ['cmn-Hans-CN'],
            'ja': ['ja-JP'],
            'hi': ['hi-IN'],
            'th': ['th-TH']
        }
    });

    ke.import('ext.arr', function () {
        for (var k in ke.ext.const.lang.tuList) {
            ke.ext.const.lang.tuEnum.push(ke.ext.const.lang.tuList[k]);
            ke.ext.const.lang.tuEnumForG =
                ke.ext.arr.pushUnique(ke.ext.const.lang.tuEnumForG, ke.ext.const.lang.tuList[k].split('-').shift());
        }
    });

})();